### ISSUE TITLE
Upload short course video(s) to Youtube channel

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/egu22pygmt#17]
Thread to coordinate upload of tutorial videos to https://www.youtube.com/c/TheGenericMappingTools, continuing from https://github.com/GenericMappingTools/egu22pygmt/issues/1#issuecomment-1129186759.

For convenience, here's a link to all the videos:

- Introduction https://github.com/GenericMappingTools/egu22pygmt/pull/10#issuecomment-1130824654
- Anatomy of a PyGMT figure https://github.com/GenericMappingTools/egu22pygmt/pull/7#issuecomment-1126111854
- Integration with the scientific Python ecosystem https://github.com/GenericMappingTools/egu22pygmt/pull/8#issuecomment-1127060648
- Making some Mars maps with pygmt https://github.com/GenericMappingTools/egu22pygmt/issues/1#issuecomment-1129409839
- LiDAR point cloud to 3D surfaces https://github.com/GenericMappingTools/egu22pygmt/pull/5#issuecomment-1126340916

@meghanrjones, let me know if you're ok to handle this? Or I can upload them (since I already have them all on my computer) if you give me permission to the Youtube channel.

In terms of licensing, looking at https://egu22.eu/guidelines/short-course_guidelines.html and https://egu22.eu/abstracts_and_programme/licence_and_copyright.html, it seems that everything will just be CC-BY-4.0 licensed which allows "Share — copy and redistribute the material in any medium or format" as long as we give proper attribution.

**Comment by maxrjones** [comment]
Yes, happy to either upload them, add you to the permissions list, or both.

**Comment by weiji14** [comment]
Do you think it's better to upload the full 1hr30min video and add chapters following https://www.youtube.com/watch?v=b1Fo_M_tj6w&t=12s, or have them as 5 separate videos?

**Comment by maxrjones** [comment]
I would go with 5 separate videos in a new playlist. We could do chapters inside the section videos, but that might take too much time.

**Comment by weiji14** [comment]
Ok, I'll coordinate with you privately to get permissions to the youtube channel.

**Comment by weiji14** [comment]
And we're live on https://www.youtube.com/playlist?list=PL3GHXjKa-p6VBA_MlUP7T_ByCFYQZ5uDG :tada: Hopefully it looks ok, not too familiar with Youtube content creation :laughing:

[![image](https://user-images.githubusercontent.com/23487320/170361245-0d33b295-6ef9-43c0-b146-a2cb2feece6b.png)](https://www.youtube.com/playlist?list=PL3GHXjKa-p6VBA_MlUP7T_ByCFYQZ5uDG)

Let's find a way to add some links or embed the videos on the main README.md and the website at https://www.generic-mapping-tools.org/egu22pygmt before we close down this issue.
