### ISSUE TITLE
Pop-up EGU22 networking event 25 May 2022 at 17:00UTC/19:00CEST

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/egu22pygmt#18]
Both @meghanrjones and @andrebelem suggested at https://github.com/GenericMappingTools/website/pull/131#discussion_r827129120 and https://github.com/GenericMappingTools/egu22pygmt/issues/1#issuecomment-1135891068 that we have some sort of virtual networking event for the EGU22 conference for PyGMT.

Officially, we probably should use https://webforms.copernicus.org/EGU22/pop-up-networking to organize this, but we can use just about any platform. So, do we want this to be on:
- Zoom
- Gather.town
- Discord
- Google Meet

For the date, let's vote using https://www.when2meet.com/?15752037-Itjqh. Yes I realize this is a bit last minute :sweat_smile:

**Comment by maxrjones** [comment]
My preference would be zoom or possibly gather.town, because I am more familiar with those platforms and would open up the event more. But, I could figure out the other platforms 😄

**Comment by andrebelem** [comment]
I agree with @meghanrjones zoom works at the best in any machine here.
I just voted in when2meet @weiji14 
😀

**Comment by weiji14** [comment]
Ok, I've scheduled a Zoom event for tomorrow (25 May) at [17:00 UTC/19:00 CEST/ 13:00 EDT](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Networking+with+the+PyGMT+team&iso=20220525T19&p1=259). See you all there!

[![image](https://user-images.githubusercontent.com/23487320/170128278-9114092b-2edd-4445-bdcc-347f34492be1.png)
](https://webforms.copernicus.org/EGU22/pop-up-networking-events)

Details can be found at https://webforms.copernicus.org/EGU22/pop-up-networking-events

**Comment by andrebelem** [comment]
Great ! Do you have any idea about how many people are clicking-watching ? I just saw a question in the pygmt forum and I think yes! if it's an event outside EGU, anyone can participate, right ?

**Comment by leouieda** [comment]
I may be able to join but I have 4h of back-to-back online meetings until 17:30. So I may be Zoomed out by then 😵

**Comment by weiji14** [comment]
> Great ! Do you have any idea about how many people are clicking-watching ? I just saw a question in the pygmt forum and I think yes! if it's an event outside EGU, anyone can participate, right ?

No idea about the click-watchers on Vimeo, and not sure if we can access those statistics, but looking at https://github.com/GenericMappingTools/egu22pygmt/graphs/traffic, there was a healthy spike of about 100 unique visitors (the blue line) yesterday and about 50 today so far to this GitHub repo, 88 of which were from the EGU22 copernicus website, so you can make an educated guess around that number :wink:

![image](https://user-images.githubusercontent.com/23487320/170363086-8895a364-f19e-48a2-952a-de3fad04b04f.png)

We've just got the videos uploaded as a Youtube playlist though at https://www.youtube.com/playlist?list=PL3GHXjKa-p6VBA_MlUP7T_ByCFYQZ5uDG and those views will be easier to track

> I may be able to join but I have 4h of back-to-back online meetings until 17:30. So I may be Zoomed out by then dizzy_face

Don't worry Leo, we've had a decent turnout of 5 people and some great discussion, a lot centered around how we managed to get people to jump from GMT5 straight to PyGMT :wink: It's nice to see random groups all over the world finding out about PyGMT, now we just need to rope in more maintainers :slightly_smiling_face:

I'll close this issue since the pop-up networking event is over.
